required: sudo

services:
  - docker

before_install:
  - docker build -t faisalsulhan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true faisalsulhan/react-test npm test

after_success:
  - docker build -t faisalsulhan/multi-client ./client
  - docker build -t faisalsulhan/multi-nginx ./nginx
  - docker build -t faisalsulhan/multi-server ./server
  - docker build -t faisalsulhan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push faisalsulhan/multi-client
  - docker push faisalsulhan/multi-nginx
  - docker push faisalsulhan/multi-server
  - docker push faisalsulhan/multi-worker